export const SITE = {
  website: "https://geoffgodwin.com/",
  author: "Geoff Godwin",
  handle: "geoff.godwin",
  tagline: "Perpetual Practitioner",
  profile: "https://github.com/geoffgodwin",
  desc: "Staff Engineer writing about agentic AI architecture, enterprise systems, and building things that actually work in production.",
  title: "Geoff Godwin",
  ogImage: "og-image.webp",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showGalleries: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Suggest edit",
    url: "https://github.com/geoffgodwin/geoffgodwin.com/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/New_York",
  introAudio: {
    enabled: false,
    src: "/audio/intro-web.mp3",
    label: "INTRO.MP3",
    duration: 30,
  },
} as const;